### ISSUE TITLE
Recommend a domain to host the playground

### ISSUE THREAD

**Issue by ahnafyy** [ahnafyy/mama-lang#6]
It would be nice to have the playground not be on https://ahnafyy.github.io/mama-lang/ but on a domain.

I would prefer to keep the budget under 100$ if possible 
SO NOT THIS
<img width="1209" alt="Screenshot 2024-01-21 at 8 32 20 PM" src="https://github.com/ahnafyy/mama-lang/assets/52210609/1deaf217-2629-4c47-914d-3e55a873ac53">

Please recommend what you think the domain should be

**Comment by zhshakib** [comment]
![image](https://github.com/ahnafyy/mama-lang/assets/46226834/caab754b-60a5-4470-9001-ab3b66f8c8aa)

This would be great. Per my research, the maximum language is hosted under the .org domain name, but this one is so cheap and doesn't make much difference.

**Comment by Aryan3212** [comment]
mamalang.dev?
<img width="1186" alt="image" src="https://github.com/ahnafyy/mama-lang/assets/57558971/2bf8cfd1-a641-4c85-9244-8144e8b73acb">

**Comment by ahnafyy** [comment]
I just bought it.

<img width="1236" alt="Screenshot 2024-01-22 at 11 00 14 PM" src="https://github.com/ahnafyy/mama-lang/assets/52210609/5cc91365-a8c1-403b-8e5c-2fe058020f75">

Will configure with https://gist.github.com/plembo/84f80c920bb5ac6f19e53fe6f8db1ff7 when I have some more time!
Thanks @Aryan3212 @zhshakib
